apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  labels:
    backup.appconnect.ibm.com/component: integrationruntime
  name: tea-tekton-cp4i
  namespace: cp4i
spec:
  flowType:
    toolkitFlow: true
  license:
    accept: true
    license: L-UAZF-8ZYQDD
    use: AppConnectEnterpriseNonProductionFREE
  template:
    spec:
      containers:
        - image: >-
            DOCKER_REGISTRY/tea-tekton-cp4i:IMAGE_TAG
          imagePullPolicy: Always
          name: runtime
          resources:
            requests:
              cpu: 300m
              memory: 368Mi
      imagePullSecrets:
        - name: regcred
  configurations:
    - teajdbc-policy
    - default-policy
    - teajdbc
  version: 12.0.10.0-r3